=== eurostat/EU-SILC/XML_CONFIG/XSD/COMP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="COMP">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="threshold" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="variable" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="threshold">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tol" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="context" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="EUROMOD"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="tol">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_tol">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="NEG"/>
								<xs:enumeration value="NMISS"/>
								<xs:enumeration value="ZERO"/>
								<xs:enumeration value="POS"/>
								<xs:enumeration value="YTY"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ST_tol">
		<xs:restriction base="xs:decimal"/>
	</xs:simpleType>
	<xs:element name="variable">
		<xs:complexType>
			<xs:attribute name="context" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value=""/>
						<xs:pattern value="EUROMOD"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[D,R,H,P]{1}[0-z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="w" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[D,R,H,P]{1}[0-z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="C"/>
						<xs:enumeration value="D"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="tol" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="desc" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Y"/>
						<xs:enumeration value="N"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reqfm2" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Y"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reqfm3" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Y"/>
						<xs:enumeration value="S"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reqfm4" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Y"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reqfm5" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Y"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/COMP/COMP-R-2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by  (European Commission - DG EUROSTAT) -->
<!-- Revision history: Mar 1st 2022 -->
<COMP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/COMP.xsd">
	<threshold context="">
		<tol type="NMISS">0.05</tol>
		<tol type="NEG">0.05</tol>
		<tol type="ZERO">1.00</tol>
		<tol type="POS">1.00</tol>
		<tol type="YTY">0.05</tol>
	</threshold>
	<threshold context="EUROMOD">
		<tol type="NMISS">0.99</tol>
		<tol type="NEG">0.99</tol>
		<tol type="ZERO">0.99</tol>
		<tol type="POS">0.99</tol>
		<tol type="YTY">0.05</tol>
	</threshold>
	<!-- CONTINUOUS VARIABLES -->
	<variable id="HY010" type="C" w="DB090" desc="Y"/>
	<variable id="HY020" type="C" w="DB090" desc="Y"/>
	<variable id="HY022" type="C" w="DB090" desc="Y"/>
	<variable id="HY023" type="C" w="DB090" desc="Y"/>
	<variable id="HY040N" type="C" w="DB090" desc="Y"/>
	<variable id="HY050N" type="C" w="DB090" desc="Y"/>
	<variable id="HY060N" type="C" w="DB090" desc="Y"/>
	<variable id="HY070N" type="C" w="DB090" desc="Y"/>
	<variable id="HY080N" type="C" w="DB090" desc="Y"/>
	<variable id="HY081N" type="C" w="DB090" desc="Y"/>
	<variable id="HY090N" type="C" w="DB090" desc="Y"/>
	<variable id="HY100N" type="C" w="DB090" desc="Y"/>
	<variable id="HY110N" type="C" w="DB090" desc="Y"/>
	<variable id="HY120N" type="C" w="DB090" desc="Y"/>
	<variable id="HY130N" type="C" w="DB090" desc="Y"/>
	<variable id="HY131N" type="C" w="DB090" desc="Y"/>
	<variable id="HY140N" type="C" w="DB090" desc="Y"/>
	<variable id="HY145N" type="C" w="DB090" desc="Y"/>
	<variable id="HY170N" type="C" w="DB090" desc="Y"/>
	<variable id="HY040G" type="C" w="DB090" desc="Y"/>
	<variable id="HY050G" type="C" w="DB090" desc="Y"/>
	<variable id="HY060G" type="C" w="DB090" desc="Y"/>
	<variable id="HY070G" type="C" w="DB090" desc="Y"/>
	<variable id="HY080G" type="C" w="DB090" desc="Y"/>
	<variable id="HY081G" type="C" w="DB090" desc="Y"/>
	<variable id="HY090G" type="C" w="DB090" desc="Y"/>
	<variable id="HY100G" type="C" w="DB090" desc="Y"/>
	<variable id="HY110G" type="C" w="DB090" desc="Y"/>
	<variable id="HY120G" type="C" w="DB090" desc="Y"/>
	<variable id="HY130G" type="C" w="DB090" desc="Y"/>
	<variable id="HY131G" type="C" w="DB090" desc="Y"/>
	<variable id="HY140G" type="C" w="DB090" desc="Y"/>
	<variable id="HY170G" type="C" w="DB090" desc="Y"/>
	<variable id="HH060" type="C" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="HH070" type="C" w="DB090" desc="Y"/>
	<variable id="PY010N" type="C" w="PB040" desc="Y"/>
	<variable id="PY020N" type="C" w="PB040" desc="Y"/>
	<variable id="PY021N" type="C" w="PB040" desc="Y"/>
	<variable id="PY035N" type="C" w="PB040" desc="Y"/>
	<variable id="PY050G" type="C" w="PB040" desc="Y"/>
	<variable id="PY050N" type="C" w="PB040" desc="Y"/>
	<variable id="PY080N" type="C" w="PB040" desc="Y"/>
	<variable id="PY090N" type="C" w="PB040" desc="Y"/>
	<variable id="PY100N" type="C" w="PB040" desc="Y"/>
	<variable id="PY110N" type="C" w="PB040" desc="Y"/>
	<variable id="PY120N" type="C" w="PB040" desc="Y"/>
	<variable id="PY130N" type="C" w="PB040" desc="Y"/>
	<variable id="PY140N" type="C" w="PB040" desc="Y"/>
	<variable id="PY010G" type="C" w="PB040" desc="Y"/>
	<variable id="PY020G" type="C" w="PB040" desc="Y"/>
	<variable id="PY021G" type="C" w="PB040" desc="Y"/>
	<variable id="PY030G" type="C" w="PB040" desc="Y"/>
	<variable id="PY035G" type="C" w="PB040" desc="Y"/>
	<variable id="PY050G" type="C" w="PB040" desc="Y"/>
	<variable id="PY080G" type="C" w="PB040" desc="Y"/>
	<variable id="PY090G" type="C" w="PB040" desc="Y"/>
	<variable id="PY100G" type="C" w="PB040" desc="Y"/>
	<variable id="PY110G" type="C" w="PB040" desc="Y"/>
	<variable id="PY120G" type="C" w="PB040" desc="Y"/>
	<variable id="PY130G" type="C" w="PB040" desc="Y"/>
	<variable id="PY140G" type="C" w="PB040" desc="Y"/>
 	<!-- CONTINUOUS VARIABLES ADDED IN 2022-->
        <variable id="HB100" type="C" w="DB090" desc="Y"/>
        <variable id="HB120" type="C" w="DB090" desc="Y"/>
        <variable id="HH071" type="C" w="DB090" reqfm2="Y" desc="Y"/>
        <variable id="HY051G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY052G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY053G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY054G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY061G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY062G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY063G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY064G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY071G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY072G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY073G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY074G" type="C" w="DB090" reqfm5="Y" desc="Y"/>
        <variable id="HY121G" type="C" w="DB090" reqfm2="Y" desc="Y"/>
        <variable id="HY121N" type="C" w="DB090" reqfm2="Y" desc="Y"/>
        <variable id="PB120" type="C" w="PB040" reqfm3="Y" desc="Y"/>
        <variable id="PL060" type="C" w="PB040" reqfm2="Y" desc="Y"/>
        <variable id="PL100" type="C" w="PB040" reqfm2="Y" reqfm4="Y" desc="Y"/>
        <variable id="PL271" type="C" w="PB040" reqfm2="Y" desc="Y"/>
        <variable id="PY091G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY092G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY093G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY094G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY101G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY102G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY103G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY104G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY111G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY112G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY113G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY114G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY121G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY122G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY123G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY124G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY131G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY132G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY133G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY134G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY141G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY142G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY143G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="PY144G" type="C" w="PB040" reqfm5="Y" desc="Y"/>
        <variable id="RB285" type="C" w="RB050" reqfm2="Y" desc="Y"/>
        <variable id="RL010" type="C" w="RB050" reqfm2="Y" desc="Y"/>
        <variable id="RL020" type="C" w="RB050" reqfm2="Y" desc="Y"/>
        <variable id="RL030" type="C" w="RB050" reqfm2="Y" desc="Y"/>
        <variable id="RL040" type="C" w="RB050" reqfm2="Y" desc="Y"/>
        <variable id="RL050" type="C" w="RB050" reqfm2="Y" desc="Y"/>
        <variable id="RL060" type="C" w="RB050" reqfm2="Y" desc="Y"/>


	<!-- DISCRETE VARIABLES -->
	<variable id="DB100" type="D" w="DB090" desc="Y"/>
	<variable id="DB120" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="DB130" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="DB135" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="RB090" type="D" w="RB050" desc="Y"/>
	<variable id="RB200" type="D" w="RB050" desc="Y"/>
	<variable id="RB245" type="D" w="RB050" desc="Y"/>
	<variable id="RB250" type="D" w="RB050" reqfm2="Y" desc="Y"/>
	<variable id="HS011" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="HS021" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="HS031" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="HS040" type="D" w="DB090" desc="Y"/>
	<variable id="HS050" type="D" w="DB090" desc="Y"/>
	<variable id="HS060" type="D" w="DB090" desc="Y"/>
	<variable id="HS090" type="D" w="DB090" desc="Y"/>
	<variable id="HS110" type="D" w="DB090" desc="Y"/>
	<variable id="HS120" type="D" w="DB090" desc="Y"/>
	<variable id="HS150" type="D" w="DB090" reqfm2="Y" desc="Y"/>
	<variable id="HH010" type="D" w="DB090" desc="Y"/>
	<variable id="HH021" type="D" w="DB090" desc="Y"/>
	<variable id="HH030" type="D" w="DB090" desc="Y"/>
	<variable id="HH050" type="D" w="DB090" desc="Y"/>
	<variable id="PB150" type="D" w="PB040" desc="Y"/>
	<variable id="PB190" type="D" w="PB040" desc="Y"/>
	<variable id="PB200" type="D" w="PB040" desc="Y"/>
	<variable id="PE010" type="D" w="PB040" desc="Y"/>
	<variable id="PL032" type="D" w="PB040" desc="Y"/>
	<variable id="PL040A" type="D" w="PB040" reqfm2="Y" desc="Y"/>
	<variable id="PL040B" type="D" w="PB040" reqfm2="Y" desc="Y"/>
	<variable id="PL051A" type="D" w="PB040" reqfm2="Y" desc="Y"/>
	<variable id="PL051B" type="D" w="PB040" reqfm2="Y" desc="Y"/>
	<variable id="PL073" type="D" w="PB040" desc="Y"/>
	<variable id="PL074" type="D" w="PB040" desc="Y"/>
	<variable id="PL075" type="D" w="PB040" desc="Y"/>
	<variable id="PL076" type="D" w="PB040" desc="Y"/>
	<variable id="PL080" type="D" w="PB040" desc="Y"/>
	<variable id="PL085" type="D" w="PB040" desc="Y"/>
	<variable id="PL086" type="D" w="PB040" desc="Y"/>
