=== eurostat/EU-SILC/XML_CONFIG/XSD/LVAL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2018 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="check">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="loop" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="title" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="subtype" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="selresp" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="select" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="from" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="join" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="join2" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on2" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="join3" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on3" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="join4" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="on4" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="where" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="group" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="having" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="start" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="end" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="category" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="cross-sectional"/>
						<xs:enumeration value="longitudinal"/>
						<xs:enumeration value="evolution"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="module" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="adhoc"/>
						<xs:enumeration value="recur3"/>
						<xs:enumeration value="recur6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="from">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="group">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="having">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join2">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join3">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="join4">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="D"/>
				<xs:enumeration value="R"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="d"/>
				<xs:enumeration value="r"/>
				<xs:enumeration value="h"/>
				<xs:enumeration value="p"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LVAL">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="preprocessing" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="check" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="globalID">
			<xs:selector xpath="check"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="on">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="on2">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="on3">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="on4">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="select">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="subtype">
		<xs:complexType/>
	</xs:element>
	<xs:element name="selresp">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Y"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="where" type="xs:string"/>
	<xs:element name="loop">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="x" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="x">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[D,R,H,P]{1}[0-z]+"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="step">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="preprocessing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="step" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/LVAL/LVAL-R-2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by  (European Commission - DG EUROSTAT) -->
<!-- Revision:  December 9th 2022 -->
<LVAL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/LVAL.xsd">
	<preprocessing>
		<step>HH_AGE_0_15</step>
		<step>HH_PK010_F</step>
		<step>HH_RL020</step>
                <step>RL010_060_SUM</step>
                <step>PAR_CHI_AGE_DIFF</step>
	</preprocessing>
  <!-- IDENTIFIERS -->
  <check id="190">
    <title>Structural - Error: DB030 - Household ID must be unique</title>
    <select>DB020, DB010,DB030</select>
    <from>d</from>
    <group>DB010,DB030</group>
    <having>count(*) gt 1 </having>
  </check>
  <check id="191">
    <title>Structural - Error: HB030 - Household ID must be unique</title>
    <select>HB020,HB010,HB030</select>
    <from>h</from>
    <group>HB010,HB030</group>
    <having>count(*) gt 1 </having>
  </check>
  <check id="192">
    <title>Structural - Error: RB030 - Personal ID must be unique when RB110 not equal to 5 </title>
    <select>RB020,RB010,RB030,RB110</select>
    <from>r</from>
    <where>RB110 ne 5</where>
    <group>RB010,RB030</group>
    <having>count(*) gt 1 </having>
  </check>
  <check id="193">
    <title>Structural - Error: PB030 - Personal ID must be unique</title>
    <select>PB020,PB010,PB030</select>
    <from>p</from>
    <group>PB010,PB030</group>
    <having>count(*) gt 1 </having>
  </check>
  <check id="194">
    <title>Structural - Error: RB030 RB040 - R-file filled in but corresponding household does not exist in D-file</title>
    <select>DB010,DB030,RB010,RB030,RB040</select>
    <from>r</from>
    <join>d</join>
    <on>RB040 = DB030 and RB010 = DB010</on>
    <where>DB030 = .</where>
  </check>
  <check id="195">
    <title>Structural - Error: HB030 - H-file filled in but corresponding household does not exist in D-file</title>
    <select>DB010,DB030,HB010,HB030</select>
    <from>h</from>
    <join>d</join>
    <on>HB030 = DB030 and HB010 = DB010</on>
    <where>DB030 = .</where>
  </check>
  <check id="196">
    <title>Structural - Error: PB030 - P-file filled in but corresponding person does not exist in R-file</title>
    <select>RB010,RB030,PB010,PB030</select>
    <from>p</from>
    <join>r</join>
    <on>PB030 = RB030 and PB010 = RB010</on>
    <where>RB030 = .</where>
  </check>
	<!-- WEIGHTS -->
	<check id="001">
		<title>Weights - Error: DB090 - Household (DB090) vs Personal (RB050) cross-sectional weight mismatch</title>
		<select>a.DB010,a.DB030,a.DB090,b.RB050</select>
		<from>d</from>
		<join>r</join>
		<on>DB030 = RHID and DB010 = RB010</on>
		<where>(DB090 ge 0) AND (RB050 ge 0) AND (ABS(DB090 - RB050) gt 0.01*DB090)</where>
	</check>
	<!-- FIGURES: EQUALITIES, INEQUALITIES OR OUTLIERS  -->
	<check id="551">
		<title>Income - Error: HY020 - No disposable household income , but components with income</title>
		<select>HB010,HB030,HY020,NET20</select>
		<from>h</from>
		<where>HY020 = 0 and sum(NET20,0) ne 0</where>
	</check>
	<check id="550">
		<title>Income - Error: HY010 - No total household income , but components with income</title>
		<select>HB010,HB030,HY010,HNETINC,HGROINC,PB030,PNETINC,PGROINC</select>
		<from>h</from>
		<join>p</join>
		<on>HB030 = PHID and HB010 = PB010</on>
		<group>HB030,HB010</group>
		<having>HY010 = 0 and sum(HNETINC,HGROINC,PNETINC,PGROINC,0) ne 0 and HGROINC ne 0</having>
	</check>
	<check id="560">
		<title>Income - Warning: HY010 - Great difference between total and components</title>
		<select>HB010,HB030,HY010,gross</select>
		<from>h</from>
		<where>(HY010  GT  0) AND (HY010 lt gross * 0.9 OR HY010 gt gross * 1.1)</where>
	</check>
	<check id="565">
		<title>Income - Warning: HY020 - Should be equal or greater than HY022 (except if pay-backs are taken into account)</title>
		<select>HB010,HB030,HY020,HY022</select>
		<from>h</from>
		<where>HY020  GT  0 and  HY022  GT  HY020</where>
	</check>
	<check id="566">
		<title>Income - Error: HY022- Must be equal or greater HY023</title>
		<select>HB010,HB030,HY022,HY023</select>
		<from>h</from>
		<where>HY022  GT  0 and  HY023  GT  HY022</where>
	</check>
	<check id="567">
		<title>Income - Warning: HY020 - Great difference between total and components</title>
		<select>HB010,HB030,HY020,net20</select>
		<from>h</from>
		<where>HY020  GT  0 and  (HY020  LT  net20 * 0.9 or HY020  GT  net20 * 1.1)</where>
	</check>
	<check id="585">
		<title>Income - Warning: HY020 HH070 - Total housing cost &gt; total net income</title>
		<select>HB010,HB030,HY020,HH070</select>
		<from>h</from>
		<where>HH070  GT  0 and  (HH070 * 12)  GT  HY020</where>
	</check>
	<check id="586">
		<title>Income - Error: PY020G should include company car (PY021G)</title>
		<select>PB010,PB030,PY020G,PY021G</select>
		<from>p</from>
		<where>(PY020G  LT  PY021G)</where>
	</check>
	<check id="753">
		<title>Labour - Error: PL073 - PL090 - Sum of months not equal to 12 or 0</title>
		<select>PB010,PB030,PL073,PL074, PL075, PL076, PL080,PL085,PL086, PL087, PL088, PL089, PL090</select>
		<from>p</from>
		<where>sum(PL073,PL074, PL075, PL076, PL080,PL085, PL086, PL087, PL088, PL089, PL090,0) not in (12, 0)</where>
	</check>
	<check id="802">
		<title>Housing Cost - Error: Rent is higher than total housing cost</title>
		<select>HB010, HB030, HH060, HH070, HH070_F</select>
		<from>h</from>
		<where>(HH060  GT  HH070) and (HH070_F gt 0)</where>
	</check>
	<!-- SAMPLING -->
	<check id="137">
		<title>Structural - Error: RB100 - If 4 year rotational panel: Person should be sample person (applicable only for non-selected respondent countries)</title>
		<select>RB010,DB010,DB030,RB030,RB100,RB110,RB245,AGE</select>
		<from>r</from>
		<join>d</join>
		<on>DB030 = RHID and DB010 = RB010</on>
		<where>RB110 = 1 and DB110 = 9 and (RB245 in (1,2) or (RB245 = 4 and AGE ge 16)) and RB100 ne 1</where>
	</check>
	<!-- AGE-->
	<check id="168">
		<title>Labour - Error: Duration of the most recent unemployment spell: routing condition (-2) based on age improperly applied</title>
		<select>PB010,PB030, b.RB082, PL271, PL271_F</select>
		<from>p</from>
		<join>r</join>
		<on>PB030 = RB030 and PB010 = RB010</on>
		<where>(PL271_F = -2) and (b.RB082 ge 16) and (b.RB082 le 74) and (PB010 ge 2021) and (RB110 NE 5)</where>
	</check>
	<check id="169">
		<title>Labour - Error: Duration of the most recent unemployment spell: routing condition (-2) based on age was expected</title>
		<select>PB010,PB030, b.RB082, PL271, PL271_F</select>
		<from>p</from>
		<join>r</join>
		<on>PB030 = RB030 and PB010 = RB010</on>
		<where>((PL271_F ne -2) and ((b.RB082 lt 16) or (b.RB082 gt 75)) and (PB010 ge 2021)) and (RB110 NE 5)</where>
	</check>
	<check id="147">
		<title>Structural - Warning: RB080 RB090 - Age at date of interview is -1</title>
		<select>RHID,HB010,RB030,RB070,RB080,HB050,HB060</select>
		<from>h</from>
		<join>r</join>
		<on>RB010 = HB010 and RHID = HB030</on>
		<where>floor(((HB060*100+HB050) - (RB080*100+RB070))/100) = -1</where>
	</check>
	<check id="755">
		<title>Labour - Warning: PL088 Nr of Months in compulsory military service &gt; 1 but younger than 18 or older than 55</title>
		<select>PB010,PB030, b.AGE, PL088</select>
		<from>p</from>
		<join>r</join>
		<on>PB030 = RB030 and PB010 = RB010</on>
		<where>(b.AGE  LT 18 or b.AGE  GT  55) and (PL088  GT 1) and (RB110 NE 5)</where>
	</check>
	<check id="813">
		<title>Status - Warning: Self defined economic status as in compulsory military service but younger than 18 or older than 55</title>
		<select>PB010,PB030, b.AGE, PL031</select>
		<from>p</from>
		<join>r</join>
		<on>PB030 = RB030 and PB010 = RB010</on>
		<where>((b.AGE  LT 18 or b.AGE  GT  55) and PL031=9) and (RB110 NE 5)</where>
	</check>
	<check id="756">
		<title>Labour - Warning: PL031 Self defined economic status as in compulsory military service but younger than 18 or older than 55</title>
		<select>PB010,PB030, b.AGE, PL031</select>
		<from>p</from>
		<join>r</join>
		<on>PB030 = RB030 and PB010 = RB010</on>
		<where>((b.AGE  LT 18 or b.AGE  GT  55) and PL031=9) and (RB110 NE 5)</where>
	</check>
	<check id="754">
		<title>Labour - Warning:PL085  Nr of Months in Retirement &gt; 1 but younger than 27</title>
		<select>PB010,PB030, b.AGE, PL085</select>
		<from>p</from>
		<join>r</join>
		<on>PB030 = RB030 and PB010 = RB010</on>
		<where>(b.AGE  LT  27) and (PL085  GT 1) and (RB110 NE 5)</where>
	</check>
        <check id="154">
		<title>Structural - Warning: HB080 - Age of Person 1 responsible for the accomodation is below 16</title>
		<select>HB010,HB030,HB080,RB030,AGE</select>
		<from>h</from>
		<join>r</join>
		<on>HB080 = RB030 and HB010 = RB010</on>
		<where>HB080_F ge 0 and   AGE  LT  16 and (RB110 NE 5)</where>
	</check>
	<check id="156">
		<title>Structural - Warning: HB090 - Age of Person 2 responsible for the accomodation is below 16</title>
		<select>HB010,HB030,HB090,RB030,AGE</select>
		<from>h</from>
		<join>r</join>
		<on>HB090 = RB030 and HB010 = RB010</on>
		<where>HB090_F ge 0 and   AGE  LT  16 and (RB110 NE 5)</where>
	</check>
	<check id="601">
		<title>Child Care - Error: RL010 - Value of variable not possible because of age</title>
		<select>RB010,RB030,RL010,RL010_F,AGE</select>
		<from>r</from>
		<where>(RL010_F ne -2 and age gt 12)</where>
	</check>
	<check id="602">
		<title>Child Care - Error: RL020 - Value of variable not possible because of age</title>
		<select>RB010,RB030,RL020,RL020_F,AGE</select>
		<from>r</from>
		<where>(RL020_F ne -2 and age gt 12)</where>
	</check>
	<check id="603">
		<title>Child Care - Error: RL030 - Value of variable not possible because of age</title>
