=== eurostat/EU-SILC/XML_CONFIG/XSD/OUTL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2018 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="k">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="lb">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="loc"/>
				<xs:element ref="k"/>
				<xs:element ref="scal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ub">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="loc"/>
				<xs:element ref="k"/>
				<xs:element ref="scal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="loc">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="P5"/>
				<xs:enumeration value="P10"/>
				<xs:enumeration value="Q1"/>
				<xs:enumeration value="MEAN"/>
				<xs:enumeration value="P50"/>
				<xs:enumeration value="MEDIAN"/>
				<xs:enumeration value="Q3"/>
				<xs:enumeration value="P90"/>
				<xs:enumeration value="P95"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="OUTL">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="variable" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scal">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="IQR"/>
				<xs:enumeration value="STD"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="formula">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="LOG"/>
				<xs:enumeration value="STD"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="variable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="formula"/>
				<xs:element ref="lb"/>
				<xs:element ref="ub"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[D,R,H,P]{1}[0-z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/OUTL/OUTL-R-2024.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by  (European Commission - DG EUROSTAT) -->
<!-- Revision history: Feb 8th 2022 -->
<OUTL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/OUTL.xsd">
	<!-- HH GROSS INCOME -->
	<variable id="HY040G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY050G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY060G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY070G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY080G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY090G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY100G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY110G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY120G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY130G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY140G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<!-- HH NET INCOME -->
	<variable id="HY040N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY050N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY060N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY070N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY080N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY090N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY100N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY110N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY120N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY130N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY140N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY145N">
		<formula>STD</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<!-- HH OVERALL INCOME -->
	<variable id="HY010">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY020">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY022">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="HY023">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<!-- PERSONAL GROSS INCOME -->
	<variable id="PY010G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY020G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY035G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY050G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY070G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY080G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY090G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY100G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY110G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY120G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY130G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY140G">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<!-- PERSONAL NET INCOME -->
	<variable id="PY010N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY020N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY035N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY050N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY070N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY080N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY090N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
	<variable id="PY100N">
		<formula>LOG</formula>
		<lb>
			<loc>Q1</loc>
			<k>3</k>
			<scal>IQR</scal>
		</lb>
		<ub>
			<loc>Q3</loc>
			<k>3</k>
			<scal>IQR</scal>
		</ub>
	</variable>
