=== eurostat/EU-SILC/XML_CONFIG/XSD/SCL_GEO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2018 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ID">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GEO">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ID"/>
				<xs:element ref="DESC"/>
			</xs:sequence>
			<xs:attribute name="start" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="end" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="filt">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="B"/>
						<xs:enumeration value="C"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="DESC">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SCL_GEO">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GEO" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/SCL/SCL_GEO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision: Aug 30th 2022 -->
<SCL_GEO xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/SCL_GEO.xsd">
	<GEO>
		<ID>AD</ID>
		<DESC>Andorra</DESC>
	</GEO>
	<GEO>
		<ID>AE</ID>
		<DESC>United_Arab_Emirates</DESC>
	</GEO>
	<GEO>
		<ID>AF</ID>
		<DESC>Afghanistan</DESC>
	</GEO>
	<GEO>
		<ID>AG</ID>
		<DESC>Antigua_and_Barbuda</DESC>
	</GEO>
	<GEO filt="B">
		<ID>AI</ID>
		<DESC>Anguilla</DESC>
	</GEO>
	<GEO>
		<ID>AL</ID>
		<DESC>Albania</DESC>
	</GEO>
	<GEO>
		<ID>AM</ID>
		<DESC>Armenia</DESC>
	</GEO>
	<GEO>
		<ID>AO</ID>
		<DESC>Angola</DESC>
	</GEO>
	<GEO>
		<ID>AR</ID>
		<DESC>Argentina</DESC>
	</GEO>
	<GEO>
		<ID>AT</ID>
		<DESC>Austria</DESC>
	</GEO>
	<GEO>
		<ID>AU</ID>
		<DESC>Australia</DESC>
	</GEO>
	<GEO>
		<ID>AW</ID>
		<DESC>Aruba</DESC>
	</GEO>
	<GEO>
		<ID>AZ</ID>
		<DESC>Azerbaijan</DESC>
	</GEO>
	<GEO>
		<ID>BA</ID>
		<DESC>Bosnia_and_Herzegovina</DESC>
	</GEO>
	<GEO>
		<ID>BB</ID>
		<DESC>Barbados</DESC>
	</GEO>
	<GEO>
		<ID>BD</ID>
		<DESC>Bangladesh</DESC>
	</GEO>
	<GEO>
		<ID>BE</ID>
		<DESC>Belgium</DESC>
	</GEO>
	<GEO>
		<ID>BF</ID>
		<DESC>Burkina_Faso</DESC>
	</GEO>
	<GEO>
		<ID>BG</ID>
		<DESC>Bulgaria</DESC>
	</GEO>
	<GEO>
		<ID>BH</ID>
		<DESC>Bahrain</DESC>
	</GEO>
	<GEO>
		<ID>BI</ID>
		<DESC>Burundi</DESC>
	</GEO>
	<GEO>
		<ID>BJ</ID>
		<DESC>Benin</DESC>
	</GEO>
	<GEO filt="B">
		<ID>BL</ID>
		<DESC>Saint_Barthelemy</DESC>
	</GEO>
	<GEO filt="B">
		<ID>BM</ID>
		<DESC>Bermuda</DESC>
	</GEO>
	<GEO>
		<ID>BN</ID>
		<DESC>Brunei_Darussalam</DESC>
	</GEO>
	<GEO>
		<ID>BO</ID>
		<DESC>Bolivia</DESC>
	</GEO>
	<GEO>
		<ID>BR</ID>
		<DESC>Brazil</DESC>
	</GEO>
	<GEO>
		<ID>BS</ID>
		<DESC>Bahamas</DESC>
	</GEO>
	<GEO>
		<ID>BT</ID>
		<DESC>Bhutan</DESC>
	</GEO>
	<GEO>
		<ID>BW</ID>
		<DESC>Botswana</DESC>
	</GEO>
	<GEO>
		<ID>BY</ID>
		<DESC>Belarus</DESC>
	</GEO>
	<GEO>
		<ID>BZ</ID>
		<DESC>Belize</DESC>
	</GEO>
	<GEO>
		<ID>CA</ID>
		<DESC>Canada</DESC>
	</GEO>
	<GEO>
		<ID>CD</ID>
		<DESC>Democratic_Republic_of_the_Congo</DESC>
	</GEO>
	<GEO>
		<ID>CF</ID>
		<DESC>Central_African_Republic</DESC>
	</GEO>
	<GEO>
		<ID>CG</ID>
		<DESC>Congo</DESC>
	</GEO>
	<GEO>
		<ID>CH</ID>
		<DESC>Switzerland</DESC>
	</GEO>
	<GEO>
		<ID>CI</ID>
		<DESC>Cote_de_Ivoire</DESC>
	</GEO>
	<GEO filt="B">
		<ID>CK</ID>
		<DESC>Cook_islands</DESC>
	</GEO>
	<GEO>
		<ID>CL</ID>
		<DESC>Chile</DESC>
	</GEO>
	<GEO>
		<ID>CM</ID>
		<DESC>Cameroon</DESC>
	</GEO>
	<GEO>
		<ID>CN</ID>
		<DESC>China</DESC>
	</GEO>
	<GEO>
		<ID>CO</ID>
		<DESC>Colombia</DESC>
	</GEO>
	<GEO>
		<ID>CR</ID>
		<DESC>Costa</DESC>
	</GEO>
	<GEO>
		<ID>CU</ID>
		<DESC>Cuba</DESC>
	</GEO>
	<GEO>
		<ID>CV</ID>
		<DESC>Cape</DESC>
	</GEO>
	<GEO>
		<ID>CW</ID>
		<DESC>Curacao</DESC>
	</GEO>
	<GEO>
		<ID>CY</ID>
		<DESC>Cyprus</DESC>
	</GEO>
	<GEO>
		<ID>CZ</ID>
		<DESC>Czechia</DESC>
	</GEO>
	<GEO>
		<ID>DE</ID>
		<DESC>Germany</DESC>
	</GEO>
	<GEO>
		<ID>DJ</ID>
		<DESC>Djibouti</DESC>
	</GEO>
	<GEO>
		<ID>DK</ID>
		<DESC>Denmark</DESC>
	</GEO>
	<GEO>
		<ID>DM</ID>
		<DESC>Dominica</DESC>
	</GEO>
	<GEO>
		<ID>DO</ID>
		<DESC>Dominican_Republic</DESC>
	</GEO>
	<GEO>
		<ID>DZ</ID>
		<DESC>Algeria</DESC>
	</GEO>
	<GEO>
		<ID>EC</ID>
		<DESC>Ecuador</DESC>
	</GEO>
	<GEO>
		<ID>EE</ID>
		<DESC>Estonia</DESC>
	</GEO>
	<GEO>
		<ID>EG</ID>
		<DESC>Egypt</DESC>
	</GEO>
	<GEO>
		<ID>EH</ID>
		<DESC>Western_Sahara</DESC>
	</GEO>
	<GEO>
		<ID>EL</ID>
		<DESC>Greece</DESC>
	</GEO>
	<GEO>
		<ID>ER</ID>
		<DESC>Eritrea</DESC>
	</GEO>
	<GEO>
		<ID>ES</ID>
		<DESC>Spain</DESC>
	</GEO>
	<GEO>
		<ID>ET</ID>
		<DESC>Ethiopia</DESC>
	</GEO>
	<GEO>
		<ID>FI</ID>
		<DESC>Finland</DESC>
	</GEO>
	<GEO>
		<ID>FJ</ID>
		<DESC>Fiji</DESC>
	</GEO>
	<GEO filt="B">
		<ID>FK</ID>
		<DESC>Falkland_islands</DESC>
	</GEO>
	<GEO>
		<ID>FM</ID>
		<DESC>Federated_States_of_Micronesia</DESC>
	</GEO>
	<GEO filt="B">
		<ID>FO</ID>
		<DESC>Faroe_Islands</DESC>
	</GEO>
	<GEO>
		<ID>FR</ID>
		<DESC>France</DESC>
	</GEO>
	<GEO>
		<ID>GA</ID>
		<DESC>Gabon</DESC>
	</GEO>
	<GEO>
		<ID>GD</ID>
		<DESC>Grenada</DESC>
	</GEO>
	<GEO>
		<ID>GE</ID>
		<DESC>Georgia</DESC>
	</GEO>
	<GEO filt="B">
		<ID>GG</ID>
		<DESC>Guernsey</DESC>
	</GEO>
	<GEO>
		<ID>GH</ID>
		<DESC>Ghana</DESC>
	</GEO>
	<GEO filt="B">
		<ID>GI</ID>
		<DESC>Gibraltar</DESC>
	</GEO>
	<GEO filt="B">
		<ID>GL</ID>
		<DESC>Greendland</DESC>
	</GEO>
	<GEO>
		<ID>GM</ID>
		<DESC>Gambia</DESC>
	</GEO>
	<GEO>
		<ID>GN</ID>
		<DESC>Guinea</DESC>
	</GEO>
	<GEO>
		<ID>GQ</ID>
		<DESC>Equatorial_Guinea</DESC>
	</GEO>
	<GEO>
		<ID>GT</ID>
		<DESC>Guatemala</DESC>
	</GEO>
	<GEO>
		<ID>GW</ID>
		<DESC>Guinea_Bissau</DESC>
	</GEO>
	<GEO>
		<ID>GY</ID>
		<DESC>Guyana</DESC>
	</GEO>
	<GEO>
		<ID>HN</ID>
		<DESC>Honduras</DESC>
	</GEO>
	<GEO>
		<ID>HR</ID>
		<DESC>Croatia</DESC>
	</GEO>
	<GEO>
		<ID>HT</ID>
		<DESC>Haiti</DESC>
	</GEO>
	<GEO>
		<ID>HU</ID>
		<DESC>Hungary</DESC>
	</GEO>
	<GEO>
		<ID>ID</ID>
		<DESC>Indonesia</DESC>
	</GEO>
	<GEO>
		<ID>IE</ID>
		<DESC>Ireland</DESC>
	</GEO>
	<GEO>
		<ID>IL</ID>
		<DESC>Israel</DESC>
	</GEO>
	<GEO filt="B">
		<ID>IM</ID>
		<DESC>Isle_of_Man</DESC>
	</GEO>
	<GEO>
		<ID>IN</ID>
		<DESC>India</DESC>
	</GEO>
	<GEO>
		<ID>IQ</ID>
		<DESC>Iraq</DESC>
	</GEO>
	<GEO>
		<ID>IR</ID>
		<DESC>Iran</DESC>
	</GEO>
	<GEO>
		<ID>IS</ID>
		<DESC>Iceland</DESC>
	</GEO>
	<GEO>
		<ID>IT</ID>
		<DESC>Italy</DESC>
	</GEO>
	<GEO filt="B">
		<ID>JE</ID>
		<DESC>Jersey</DESC>
	</GEO>
	<GEO>
		<ID>JM</ID>
		<DESC>Jamaica</DESC>
	</GEO>
	<GEO>
		<ID>JO</ID>
		<DESC>Jordan</DESC>
	</GEO>
	<GEO>
		<ID>JP</ID>
		<DESC>Japan</DESC>
	</GEO>
	<GEO>
		<ID>KE</ID>
		<DESC>Kenya</DESC>
	</GEO>
	<GEO>
		<ID>KG</ID>
		<DESC>Kyrgyzstan</DESC>
	</GEO>
	<GEO>
		<ID>KH</ID>
		<DESC>Cambodia</DESC>
	</GEO>
	<GEO>
		<ID>KI</ID>
		<DESC>Kiribati</DESC>
	</GEO>
	<GEO>
		<ID>KM</ID>
		<DESC>Comoros</DESC>
	</GEO>
	<GEO>
		<ID>KN</ID>
		<DESC>Saint_Kitts_and_Nevis</DESC>
	</GEO>
	<GEO>
		<ID>KP</ID>
		<DESC>North_Korea</DESC>
	</GEO>
	<GEO>
		<ID>KR</ID>
		<DESC>South_Korea</DESC>
	</GEO>
	<GEO>
		<ID>KW</ID>
		<DESC>Kuwait</DESC>
	</GEO>
	<GEO filt="B">
		<ID>KY</ID>
		<DESC>Cayman_islands</DESC>
	</GEO>
	<GEO>
		<ID>KZ</ID>
		<DESC>Kazakhstan</DESC>
	</GEO>
	<GEO>
		<ID>LA</ID>
		<DESC>Laos</DESC>
	</GEO>
	<GEO>
		<ID>LB</ID>
		<DESC>Lebanon</DESC>
	</GEO>
	<GEO>
		<ID>LC</ID>
		<DESC>Saint_Lucia</DESC>
	</GEO>
	<GEO>
		<ID>LI</ID>
		<DESC>Liechtenstein</DESC>
	</GEO>
	<GEO>
		<ID>LK</ID>
		<DESC>Sri</DESC>
	</GEO>
	<GEO>
		<ID>LR</ID>
		<DESC>Liberia</DESC>
	</GEO>
	<GEO>
		<ID>LS</ID>
		<DESC>Lesotho</DESC>
	</GEO>
	<GEO>
		<ID>LT</ID>
		<DESC>Lithuania</DESC>
	</GEO>
	<GEO>
		<ID>LU</ID>
		<DESC>Luxembourg</DESC>
	</GEO>
	<GEO>
		<ID>LV</ID>
		<DESC>Latvia</DESC>
	</GEO>
	<GEO>
		<ID>LY</ID>
		<DESC>Libya</DESC>
	</GEO>
	<GEO>
		<ID>MA</ID>
		<DESC>Morocco</DESC>
	</GEO>
	<GEO>
		<ID>MC</ID>
		<DESC>Monaco</DESC>
	</GEO>
	<GEO>
		<ID>MD</ID>
		<DESC>Moldova</DESC>
	</GEO>
	<GEO>
		<ID>ME</ID>
		<DESC>Montenegro</DESC>
	</GEO>
	<GEO filt="B">
		<ID>MF</ID>
		<DESC>Saint_Martin</DESC>
	</GEO>
	<GEO>
		<ID>MG</ID>
		<DESC>Madagascar</DESC>
	</GEO>
	<GEO>
		<ID>MH</ID>
		<DESC>Marshall_Islands</DESC>
	</GEO>
	<GEO>
		<ID>MK</ID>
		<DESC>North_Macedonia</DESC>
	</GEO>
	<GEO>
		<ID>ML</ID>
		<DESC>Mali</DESC>
	</GEO>
	<GEO>
		<ID>MM</ID>
		<DESC>Myanmar_Burma</DESC>
	</GEO>
	<GEO>
		<ID>MN</ID>
		<DESC>Mongolia</DESC>
	</GEO>
	<GEO>
		<ID>MR</ID>
		<DESC>Mauritania</DESC>
	</GEO>
	<GEO filt="B">
		<ID>MS</ID>
		<DESC>Montserrat</DESC>
	</GEO>
	<GEO>
		<ID>MT</ID>
		<DESC>Malta</DESC>
	</GEO>
	<GEO>
		<ID>MU</ID>
		<DESC>Mauritius</DESC>
	</GEO>
	<GEO>
		<ID>MV</ID>
		<DESC>Maldives</DESC>
	</GEO>
	<GEO>
		<ID>MW</ID>
		<DESC>Malawi</DESC>
	</GEO>
	<GEO>
		<ID>MX</ID>
		<DESC>Mexico</DESC>
	</GEO>
	<GEO>
		<ID>MY</ID>
		<DESC>Malaysia</DESC>
	</GEO>
	<GEO>
		<ID>MZ</ID>
		<DESC>Mozambique</DESC>
	</GEO>
	<GEO>
		<ID>NA</ID>
		<DESC>Namibia</DESC>
	</GEO>
	<GEO filt="B">
		<ID>NC</ID>
		<DESC>New_Caledonia</DESC>
	</GEO>
	<GEO>
		<ID>NE</ID>
		<DESC>Niger</DESC>
	</GEO>
	<GEO>
		<ID>NG</ID>
		<DESC>Nigeria</DESC>
	</GEO>
	<GEO>
		<ID>NI</ID>
		<DESC>Nicaragua</DESC>
	</GEO>
	<GEO>
		<ID>NL</ID>
		<DESC>Netherlands</DESC>
	</GEO>
	<GEO>
		<ID>NO</ID>
		<DESC>Norway</DESC>
	</GEO>
	<GEO>
		<ID>NP</ID>
		<DESC>Nepal</DESC>
	</GEO>
	<GEO>
		<ID>NR</ID>
		<DESC>Nauru</DESC>
	</GEO>
	<GEO>
		<ID>NZ</ID>
		<DESC>New_Zealand</DESC>
	</GEO>
	<GEO>
		<ID>OM</ID>
		<DESC>Oman</DESC>
	</GEO>
	<GEO>
		<ID>PA</ID>
		<DESC>Panama</DESC>
	</GEO>
	<GEO>
		<ID>PE</ID>
		<DESC>Peru</DESC>
	</GEO>
	<GEO filt="B">
		<ID>PF</ID>
		<DESC>French Polynesia</DESC>
	</GEO>
	<GEO>
		<ID>PG</ID>
		<DESC>Papua_New_Guinea</DESC>
	</GEO>
	<GEO>
		<ID>PH</ID>
		<DESC>Philippines</DESC>
	</GEO>
	<GEO>
		<ID>PK</ID>
		<DESC>Pakistan</DESC>
	</GEO>
	<GEO>
		<ID>PL</ID>
		<DESC>Poland</DESC>
	</GEO>
	<GEO filt="B">
		<ID>PM</ID>
		<DESC>Saint_Pierre_and_Miquelon</DESC>
	</GEO>
	<GEO filt="B">
		<ID>PN</ID>
		<DESC>Pitcairn</DESC>
	</GEO>
	<GEO>
		<ID>PS</ID>
		<DESC>Palestine</DESC>
	</GEO>
	<GEO>
		<ID>PT</ID>
		<DESC>Portugal</DESC>
	</GEO>
	<GEO>
		<ID>PW</ID>
		<DESC>Palau</DESC>
	</GEO>
	<GEO>
		<ID>PY</ID>
		<DESC>Paraguay</DESC>
	</GEO>
	<GEO>
		<ID>QA</ID>
		<DESC>Qatar</DESC>
	</GEO>
	<GEO>
		<ID>RO</ID>
		<DESC>Romania</DESC>
