=== eurostat/EU-SILC/XML_CONFIG/XSD/SCL_CTRY.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2018 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ID">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GEO">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ID"/>
				<xs:element ref="DESC"/>
			</xs:sequence>
		</xs:complexType>
		<xs:attribute name="start" type="xs:integer" use="optional"/>
		<xs:attribute name="end" type="xs:integer" use="optional"/>
	</xs:element>
	<xs:element name="DESC">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SCL_CTRY">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GEO" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/SCL/SCL_CTRY.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision: Aug 30th 2022 -->
<SCL_CTRY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/SCL_CTRY.xsd">

	<GEO>
		<ID>AL</ID>
		<DESC>Albania</DESC>
	</GEO>
	<GEO>
		<ID>AT</ID>
		<DESC>Austria</DESC>
	</GEO>
	<GEO>
		<ID>BA</ID>
		<DESC>Bosnia_and_Herzegovina</DESC>
	</GEO>
	<GEO>
		<ID>BE</ID>
		<DESC>Belgium</DESC>
	</GEO>
	<GEO>
		<ID>BG</ID>
		<DESC>Bulgaria</DESC>
	</GEO>
	<GEO>
		<ID>CH</ID>
		<DESC>Switzerland</DESC>
	</GEO>
	<GEO>
		<ID>CY</ID>
		<DESC>Cyprus</DESC>
	</GEO>
	<GEO>
		<ID>CZ</ID>
		<DESC>Czechia</DESC>
	</GEO>
	<GEO>
		<ID>DE</ID>
		<DESC>Germany</DESC>
	</GEO>
	<GEO>
		<ID>DK</ID>
		<DESC>Denmark</DESC>
	</GEO>
	<GEO>
		<ID>EE</ID>
		<DESC>Estonia</DESC>
	</GEO>
	<GEO>
		<ID>EL</ID>
		<DESC>Greece</DESC>
	</GEO>
	<GEO>
		<ID>ES</ID>
		<DESC>Spain</DESC>
	</GEO>
	<GEO>
		<ID>FI</ID>
		<DESC>Finland</DESC>
	</GEO>
	<GEO>
		<ID>FR</ID>
		<DESC>France</DESC>
	</GEO>
	<GEO>
		<ID>HR</ID>
		<DESC>Croatia</DESC>
	</GEO>
	<GEO>
		<ID>HU</ID>
		<DESC>Hungary</DESC>
	</GEO>
	<GEO>
		<ID>IE</ID>
		<DESC>Ireland</DESC>
	</GEO>
	<GEO>
		<ID>IS</ID>
		<DESC>Iceland</DESC>
	</GEO>
	<GEO>
		<ID>IT</ID>
		<DESC>Italy</DESC>
	</GEO>
	<GEO>
		<ID>LI</ID>
		<DESC>Liechtenstein</DESC>
	</GEO>
	<GEO>
		<ID>LT</ID>
		<DESC>Lithuania</DESC>
	</GEO>
	<GEO>
		<ID>LU</ID>
		<DESC>Luxembourg</DESC>
	</GEO>
	<GEO>
		<ID>LV</ID>
		<DESC>Latvia</DESC>
	</GEO>
	<GEO>
		<ID>ME</ID>
		<DESC>Montenegro</DESC>
	</GEO>
	<GEO>
		<ID>MK</ID>
		<DESC>North_Macedonia</DESC>
	</GEO>
	<GEO>
		<ID>MT</ID>
		<DESC>Malta</DESC>
	</GEO>
	<GEO>
		<ID>NL</ID>
		<DESC>Netherlands</DESC>
	</GEO>
	<GEO>
		<ID>NO</ID>
		<DESC>Norway</DESC>
	</GEO>
	<GEO>
		<ID>PL</ID>
		<DESC>Poland</DESC>
	</GEO>
	<GEO>
		<ID>PT</ID>
		<DESC>Portugal</DESC>
	</GEO>
	<GEO>
		<ID>RO</ID>
		<DESC>Romania</DESC>
	</GEO>
	<GEO>
		<ID>RS</ID>
		<DESC>Serbia</DESC>
	</GEO>
	<GEO>
		<ID>SE</ID>
		<DESC>Sweden</DESC>
	</GEO>
	<GEO>
		<ID>SI</ID>
		<DESC>Slovenia</DESC>
	</GEO>
	<GEO>
		<ID>SK</ID>
		<DESC>Slovakia</DESC>
	</GEO>
	<GEO>
		<ID>TR</ID>
		<DESC>Turkiye</DESC>
	</GEO>
	<GEO>
		<ID>UK</ID>
		<DESC>United_Kingdom</DESC>
	</GEO>
	<GEO>
		<ID>XK</ID>
		<DESC>Kosovo</DESC>
	</GEO>
</SCL_CTRY>
