=== eurostat/EU-SILC/XML_CONFIG/XSD/SIZE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision: March 23rd 2023 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="nuts">
		<xs:simpleType>
			<xs:restriction base="xs:short"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hh_c">
		<xs:simpleType>
			<xs:restriction base="xs:short"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hh_l">
		<xs:simpleType>
			<xs:restriction base="xs:short"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="cntry">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="nuts" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="hh_c"/>
				<xs:element ref="hh_l"/>
			</xs:sequence>
			<xs:attribute name="id">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SIZE_TARGET">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cntry" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="globalID">
			<xs:selector xpath="cntry"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== eurostat/EU-SILC/XML_CONFIG/XML/SIZE/SIZE-2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision: March 23rd 2023 -->
<SIZE_TARGET xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/SIZE.xsd">
  <cntry id="AL">
    <nuts id="AL">
      <hh_c>3575</hh_c>
      <hh_l>1379</hh_l>
    </nuts>
    <nuts id="AL0">
      <hh_c>652</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AL01">
      <hh_c>345</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AL02">
      <hh_c>420</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AL03">
      <hh_c>357</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="AT">
    <nuts id="AT">
      <hh_c>4373</hh_c>
      <hh_l>1689</hh_l>
    </nuts>
    <nuts id="AT1">
      <hh_c>796</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT11">
      <hh_c>0</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT12">
      <hh_c>506</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT13">
      <hh_c>581</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT2">
      <hh_c>527</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT21">
      <hh_c>296</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT22">
      <hh_c>436</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT3">
      <hh_c>694</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT31">
      <hh_c>474</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT32">
      <hh_c>292</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT33">
      <hh_c>338</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="AT34">
      <hh_c>0</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="BE">
    <nuts id="BE">
      <hh_c>4606</hh_c>
      <hh_l>1780</hh_l>
    </nuts>
    <nuts id="BE1">
      <hh_c>459</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE10">
      <hh_c>460</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE2">
      <hh_c>1002</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE21">
      <hh_c>537</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE22">
      <hh_c>357</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE23">
      <hh_c>484</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE24">
      <hh_c>415</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE25">
      <hh_c>431</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE3">
      <hh_c>753</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE31">
      <hh_c>0</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE32">
      <hh_c>459</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE33">
      <hh_c>423</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE34">
      <hh_c>0</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BE35">
      <hh_c>276</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="BG">
    <nuts id="BG">
      <hh_c>4112</hh_c>
      <hh_l>1588</hh_l>
    </nuts>
    <nuts id="BG3">
      <hh_c>712</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG31">
      <hh_c>329</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG32">
      <hh_c>339</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG33">
      <hh_c>365</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG34">
      <hh_c>383</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG4">
      <hh_c>717</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG41">
      <hh_c>565</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="BG42">
      <hh_c>440</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="CH">
    <nuts id="CH">
      <hh_c>4354</hh_c>
      <hh_l>1682</hh_l>
    </nuts>
    <nuts id="CH0">
      <hh_c>1165</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH01">
      <hh_c>505</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH02">
      <hh_c>549</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH03">
      <hh_c>434</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH04">
      <hh_c>509</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH05">
      <hh_c>428</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH06">
      <hh_c>353</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CH07">
      <hh_c>0</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="CY">
    <nuts id="CY">
      <hh_c>3111</hh_c>
      <hh_l>1199</hh_l>
    </nuts>
    <nuts id="CY0">
      <hh_c>339</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CY00">
      <hh_c>341</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="CZ">
    <nuts id="CZ">
      <hh_c>4506</hh_c>
      <hh_l>1741</hh_l>
    </nuts>
    <nuts id="CZ0">
      <hh_c>1270</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ01">
      <hh_c>468</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ02">
      <hh_c>452</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ03">
      <hh_c>433</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ04">
      <hh_c>417</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ05">
      <hh_c>475</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ06">
      <hh_c>497</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ07">
      <hh_c>419</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="CZ08">
      <hh_c>425</hh_c>
      <hh_l>0</hh_l>
    </nuts>
  </cntry>
  <cntry id="DE">
    <nuts id="DE">
      <hh_c>8169</hh_c>
      <hh_l>3166</hh_l>
    </nuts>
    <nuts id="DE1">
      <hh_c>1327</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE11">
      <hh_c>811</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE12">
      <hh_c>675</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE13">
      <hh_c>601</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE14">
      <hh_c>534</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE2">
      <hh_c>1451</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE21">
      <hh_c>884</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE22">
      <hh_c>432</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE23">
      <hh_c>414</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE24">
      <hh_c>412</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE25">
      <hh_c>542</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE26">
      <hh_c>455</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE27">
      <hh_c>548</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE3">
      <hh_c>843</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE30">
      <hh_c>842</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE4">
      <hh_c>656</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE40">
      <hh_c>658</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE5">
      <hh_c>352</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE50">
      <hh_c>352</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE6">
      <hh_c>581</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE60">
      <hh_c>582</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE7">
      <hh_c>1010</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE71">
      <hh_c>814</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE72">
      <hh_c>404</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE73">
      <hh_c>442</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE8">
      <hh_c>532</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE80">
      <hh_c>533</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE9">
      <hh_c>1131</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE91">
      <hh_c>515</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE92">
      <hh_c>601</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE93">
      <hh_c>518</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DE94">
      <hh_c>621</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEA">
      <hh_c>1723</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEA1">
      <hh_c>944</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEA2">
      <hh_c>862</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEA3">
      <hh_c>643</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEA4">
      <hh_c>565</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEA5">
      <hh_c>773</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEB">
      <hh_c>805</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEB1">
      <hh_c>484</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEB2">
      <hh_c>290</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEB3">
      <hh_c>575</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEC">
      <hh_c>398</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEC0">
      <hh_c>397</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DED">
      <hh_c>854</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DED2">
      <hh_c>530</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DED4">
      <hh_c>502</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DED5">
      <hh_c>441</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEE">
      <hh_c>620</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEE0">
      <hh_c>618</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEF">
      <hh_c>692</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEF0">
      <hh_c>692</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEG">
      <hh_c>604</hh_c>
      <hh_l>0</hh_l>
    </nuts>
    <nuts id="DEG0">
